"""add favourites

Revision ID: a6321a9b7899
Revises: fe94c77da7c0
Create Date: 2026-07-21 08:08:15.678559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6321a9b7899'
down_revision: Union[str, Sequence[str], None] = 'fe94c77da7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_favourites_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_favourites_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favourites')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favourites_user_product')
    )
    op.create_index(op.f('ix_favourites_product_id'), 'favourites', ['product_id'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_product_id'), table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
