"""add product images variants and inventory

Revision ID: b4c54b868805
Revises: 04067f5cdfac
Create Date: 2026-07-17 18:46:38.764046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4c54b868805"
down_revision: Union[str, Sequence[str], None] = "04067f5cdfac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=False),
        sa.Column("alt_text", sa.String(length=250), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order >= 0", name=op.f("ck_product_images_display_order_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("size_label", sa.String(length=100), nullable=True),
        sa.Column("colour", sa.String(length=80), nullable=True),
        sa.Column("material", sa.String(length=120), nullable=True),
        sa.Column("price_paise", sa.Integer(), nullable=False),
        sa.Column("length_cm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("width_cm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("weight_grams", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm >= 0",
            name=op.f("ck_product_variants_height_non_negative"),
        ),
        sa.CheckConstraint(
            "length_cm IS NULL OR length_cm >= 0",
            name=op.f("ck_product_variants_length_non_negative"),
        ),
        sa.CheckConstraint("price_paise >= 0", name=op.f("ck_product_variants_price_non_negative")),
        sa.CheckConstraint(
            "weight_grams IS NULL OR weight_grams >= 0",
            name=op.f("ck_product_variants_weight_non_negative"),
        ),
        sa.CheckConstraint(
            "width_cm IS NULL OR width_cm >= 0", name=op.f("ck_product_variants_width_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
    )
    op.create_index(
        op.f("ix_product_variants_colour"), "product_variants", ["colour"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_material"), "product_variants", ["material"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_product_variants_sku"), "product_variants", ["sku"], unique=True)
    op.create_table(
        "inventory",
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), server_default="5", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0", name=op.f("ck_inventory_low_stock_threshold_non_negative")
        ),
        sa.CheckConstraint(
            "quantity_on_hand >= 0", name=op.f("ck_inventory_quantity_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_quantity <= quantity_on_hand",
            name=op.f("ck_inventory_reserved_not_greater_than_stock"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_inventory_reserved_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory")),
    )
    op.create_index(op.f("ix_inventory_variant_id"), "inventory", ["variant_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_variant_id"), table_name="inventory")
    op.drop_table("inventory")
    op.drop_index(op.f("ix_product_variants_sku"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_material"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_colour"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    # ### end Alembic commands ###
